##### Checks run at pull request #####
# Check that urls in the content are not broken
url-checker: yes
# Render preview of content with changes (Rmd's and md's are checked)
render-preview: yes
# Spell check Rmds and quizzes
spell-check: yes
# Style any R code
style-code: yes


###### Calendly ######
refresh-calendly: no

###### CRAN ######
refresh-cran: no
cran-packages: [ metricminer, ottrpal ]

###### GitHub ######
refresh-github: no
gh-repos: [ fhdsl/metricminer, fhdsl/metricminer.org ]

###### Google Analytics ######
refresh-ga: no
ga-property-ids: [ ]

###### Google Forms ######
refresh-googleform: no
google-forms:
  [ 1pbFfgUPYH2w9zEoCDjCa4HFOxzEhGOseufw28Xxmd-o,
  1JjmsiuVoGSxvl-1M_oWittcftO955tijzeNc-cgJlo8 ]

###### Slido ######
refresh-slido: no
drive-id: 1XWXHHyj32Uw_UyaUJrqp6S--hHnM0-7l

###### YouTube ######
refresh-youtube: no
video-ids:
 [ XN_QPRrJZAw,
   YkYnni-WuaQ ]

# What docker image should be used for rendering?
# The default is jhudsl/base_ottr:main
rendering-docker-image: 'cansav09/metricminer:latest'
