##### Checks run at pull request #####
# Check that urls in the content are not broken
url-checker: yes
# Render preview of content with changes (Rmd's and md's are checked)
render-preview: yes
# Spell check Rmds and quizzes
spell-check: yes
# Style any R code
style-code: yes


###### Calendly ######
refresh-calendly: yes

###### CRAN ######
refresh-cran: yes
cran_packages: [ metricminer, ottrpal ]

###### GitHub ######
refresh-github: yes
gh_repos: [ fhdsl/metricminer, fhdsl/metricminer.org ]

###### Google Analytics ######
refresh-ga: yes
ga_property_ids: [ 422671031, 422558989 ]

###### Google Forms ######
refresh-googleforms: yes
google_forms:
  [ 1pbFfgUPYH2w9zEoCDjCa4HFOxzEhGOseufw28Xxmd-o, 1JjmsiuVoGSxvl-1M_oWittcftO955tijzeNc-cgJlo8 ]

###### Slido ######
refresh-slido: yes
drive_id: 1XWXHHyj32Uw_UyaUJrqp6S--hHnM0-7l

###### YouTube ######
refresh-youtube: yes
video_ids: [ XN_QPRrJZAw, YkYnni-WuaQ ]

# What docker image should be used for rendering?
# The default is jhudsl/base_ottr:main
rendering-docker-image: 'cansav09/metricminer:main'
